services:
  - type: web
    name: nutrebirth-backend
    runtime: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_AUTH_COOKIE_SECURE
        value: true
      - key: APP_AUTH_COOKIE_SAME_SITE
        value: None
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
