services:
  - type: web
    name: nutrebirth-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_AUTH_COOKIE_SECURE
        value: true
      - key: APP_AUTH_COOKIE_SAME_SITE
        value: None
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
